### ISSUE TITLE
Don't tag

### ISSUE THREAD

**Issue by peterbe** [mozilla/socorrolib#8]
This might a personal preference thing so feel free to convince me otherwise.

To make a new release onto pypi you, now, need to change the version number **and** create a new tag since travis is told to [only distribute on tags](https://github.com/mozilla/socorrolib/blob/03642ce1edd96bc383ea11e9c7a467b9f6ec771f/.travis.yml#L21).

I suggest we try to push to pypi on every master build. If you change something in master without changing the version number (e.g. editing the README) pypi simply ignores it.

This means that all you need to do is edit the version number and push to master and a new release goes out to pypi.

**Comment by lonnen** [comment]
I was not certain of the behaviour for on push so I set it to tag. If it truly ignores it (instead of overwriting) when the version number is the same, I'm +1

**Comment by lonnen** [comment]
fixed in #13
