### ISSUE TITLE
let's not do eggs

### ISSUE THREAD

**Issue by willkg** [mozilla/socorrolib#9]
Right now, Travis builds a `.tar.gz` sdist and a `.egg` and then pushes them to pypi. sdist is super. egg not so much.

Turns out @jezdez wrote most of the travis deploy code. He says:

1. distributions is in the wrong place in the `.travis.yml` file--try fixing that
2. there might be a `PYPI_DISTRIBUTIONS` Travis project variable set--nix it if there is
3. we're calling `python setup.py install` in the install section for travis and that might be doing things it shouldn't (hand-waving here)

**Comment by willkg** [comment]
When travis isn't having problems pushing an sdist, then this isn't a big deal. I can look into fixing it next week.

**Comment by willkg** [comment]
Also, if it turns out to be item 1, we should let @jezdez know--could be a bug in the Travis stuff.

**Comment by lonnen** [comment]
Travis doc example also uses quotes around the distributions value. Going to try that as well.

**Comment by lonnen** [comment]
pr #13 fixes 1 and my comment

**Comment by lonnen** [comment]
pr #13 fixes this issue: https://pypi.python.org/pypi/socorrolib/0.2.0
